#!/usr/bin/python
import boto3
import sys

cloudwatch = boto3.client('cloudwatch')
paginator = cloudwatch.get_paginator('describe_alarms')
count = 0

def done(n):
    if n == 1:
        sys.exit(0)
    else:
        main()


#You can change this StateValue to either OK, ALARM, or INSUFFICIENT_DATA. We are only interested in any alarms though
for response in paginator.paginate(StateValue='ALARM'):
    #If their are no alarms then you cannot assign the response to the string varialbe so you need to use try except
    try:
        string = response['MetricAlarms'][count]['AlarmDescription']
        while True:
            print("Alarm description No.{} ".format(count+1) + string)
            count  = count + 1
            try:
                string = response['MetricAlarms'][count]['AlarmDescription']
            except:
                done(2)
    except:
        if count == 0:
            print("Nothing to alarm")
            done(1)

def main():
    print("Not exiting as 0")
sys.exit(1)
